CREATE TABLE acessos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pais TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE auth (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  pass TEXT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
